
#execution_env=local
execution_env=remote

appURL=http://localhost/opencart/
OpencartAdminURL=http://localhost/opencart/myadmin/
email=saleha03@gmail.com
password=test@123
#password=test@1234
searchProductName=iphone